
networks:
  dream_default:
    external: true

services:
  agent:
    env_file: [.env]
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run'
    build:
      context: ./
      dockerfile: dockerfile_agent
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  mongo:
    command: mongod
    image: mongo:4.0.0

  web:
    build:
      context: ./
      dockerfile: ./web_app/Dockerfile
    container_name: dream
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file: [.env]
    networks:
      - dream_default
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST=${DATABASE_HOST}
    networks:
      - dream_default

version: '3.7'
