"""init1

Revision ID: ed7030f61ebd
Revises: 
Create Date: 2023-09-18 20:08:39.834147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7030f61ebd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badlisted_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spacy_nounphrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spacy_nounphrases')
    op.drop_table('badlisted_words')
    # ### end Alembic commands ###
